let errs=[];const path=require('path');const fs=require('fs');
const {chromium}=require('C:/Users/Mario/Desktop/claude-code/BCC-Zentrale/01_Kunden/dbcc-GmbH/projekte/dbcc-360-crm/node_modules/playwright');
const http=require('http');
const root='C:/Users/Mario/Desktop/claude-code/BCC-Zentrale/03_Privat/Gesundheit';
const OUT=process.argv[2];
const plan=fs.readFileSync('C:/Users/Mario/DBCC GmbH/Mario - Dokumente/Privat/Arzt/Die Fitmacher/Gesundheits-App/mein-plan.json','utf8');
const srv=http.createServer((q,r)=>{let p=decodeURIComponent(q.url.split('?')[0]);if(p==='/')p='/index.html';const f=path.join(root,p);if(!fs.existsSync(f)){r.statusCode=404;return r.end()}const t={'.html':'text/html','.js':'text/javascript','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'}[path.extname(f)]||'text/plain';r.setHeader('content-type',t);r.end(fs.readFileSync(f))}).listen(8765,'127.0.0.1');
(async()=>{
 const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,locale:'de-AT'});const pg=await ctx.newPage();
 errs=[];pg.on('pageerror',e=>errs.push('PAGEERROR '+e.message));pg.on('console',m=>{if(m.type()==='error')errs.push('CONSOLE '+m.text())});
 console.log('goto');await pg.goto('http://127.0.0.1:8765/index.html',{waitUntil:'load'});await pg.waitForTimeout(400);
 await pg.evaluate(p=>{localStorage.setItem('gp_plan',p);localStorage.setItem('gp_set',JSON.stringify({times:{},atimes:{},notif:false,kurStart:'2026-09-14',medOverride:{}}));},plan);
 await pg.reload({waitUntil:'load'});await pg.waitForTimeout(400);
 const out=[];
 out.push('HEUTE meds: '+await pg.locator('#med-list .chk').count()+' | banner: '+(await pg.locator('#heute-banner').innerText()).replace(/\n/g,' / ').slice(0,220));
 out.push('Training: '+(await pg.locator('#train-list').innerText()).slice(0,200).replace(/\n/g,' / '));
 await pg.locator('#med-list .chk').first().click();out.push('nach Klick: '+await pg.locator('#med-count').innerText());
 await pg.locator('#sport').click();out.push('Sport an → meds: '+await pg.locator('#med-list .chk').count());
 await pg.locator('#kaffee-plus').click();await pg.locator('#kaffee-plus').click();await pg.locator('#kaffee-plus').click();out.push('Kaffee: '+await pg.locator('#kaffee-v').innerText()+' '+await pg.locator('#kaffee-hint').innerText());
 await pg.screenshot({path:OUT+'/heute.png',fullPage:true});
 await pg.locator('nav button[data-p=essen]').click();await pg.waitForTimeout(200);
 out.push('Ampel Einträge: '+await pg.locator('#food-list .food').count());
 await pg.fill('#food-q','apfel');await pg.waitForTimeout(100);out.push('Suche apfel: '+(await pg.locator('#food-list').innerText()).replace(/\n/g,' / ').slice(0,160));
 await pg.locator('#p-essen .tabs button[data-sub=woche]').click();out.push('Woche Mahlzeiten: '+await pg.locator('#woche .meal').count());
 const fleisch=await pg.evaluate(()=>{const w=JSON.parse(localStorage.getItem('gp_week'));return w.days.flatMap(d=>[d.f,d.m,d.a]).filter(id=>REZEPTE.find(r=>r.id===id).fleisch).length});out.push('Fleischgerichte/Woche: '+fleisch);
 await pg.screenshot({path:OUT+'/woche.png',fullPage:true});
 await pg.locator('#p-essen .tabs button[data-sub=einkauf]').click();out.push('Einkauf Positionen: '+await pg.locator('#einkauf .chk').count());
 await pg.locator('#p-essen .tabs button[data-sub=tipps]').click();out.push('Tipps Karten: '+await pg.locator('#tipps .card').count());
 await pg.locator('#p-essen .tabs button[data-sub=regeln]').click();out.push('Regeln Karten: '+await pg.locator('#regeln .card').count());
 await pg.locator('nav button[data-p=atmen]').click();await pg.locator('#ex-list button').first().click();await pg.locator('#b-start').click();await pg.waitForTimeout(1500);out.push('Atmen: '+(await pg.locator('#orb').innerText()).replace(/\n/g,' ')+' | '+await pg.locator('#bstat').innerText());await pg.locator('#b-stop').click();
 await pg.locator('nav button[data-p=verlauf]').click();out.push('Verlauf stats: '+(await pg.locator('#stats').innerText()).replace(/\n/g,' '));
 await pg.locator('#p-verlauf .tabs button[data-sub=befunde]').click();out.push('Befunde Tabellen-Zeilen: '+await pg.locator('#befunde table tr').count());
 await pg.screenshot({path:OUT+'/befunde.png',fullPage:true});
 await pg.locator('nav button[data-p=mehr]').click();out.push('Mehr Kur-Info: '+(await pg.locator('#kur-info').innerText()).slice(0,160));out.push('Dosis-Editor Zeilen: '+await pg.locator('#med-edit .medit').count());
 const phases=await pg.evaluate(()=>{const r={};for(const d of ['2026-09-06','2026-09-15','2026-09-17','2026-09-20','2026-09-25','2026-11-10','2026-11-25','2027-02-01']){TK=d;const kp=kurPhase();r[d]=(kp?('KurT'+kp.tag+' '+kp.name+' | '):'')+medsToday().map(m=>m.name.split(' ')[0]+' '+m.menge+m.slot+(m.paused?'(P)':'')).join(', ')}TK=todayKey();return r});
 Object.entries(phases).forEach(([d,v])=>out.push(d+': '+v));
 console.log(out.join('\n'));console.log('ERRORS:',errs.length?errs.join('\n'):'keine');
 await b.close();srv.close();process.exit(0);
})().catch(e=>{console.error('FAIL',e.message.slice(0,200));console.error('ERRS',errs.join(' | '));process.exit(1)});
